; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube
lib_archive = no
debug_init_break = tbreak main
monitor_speed = 115200
build_flags =
    -Wl,-u,_printf_float,-u,_scanf_float
    -lm
    -DSTM32F4
    -DHSE_VALUE=8000000U
    -Iinclude
    -ICommon
    -ICommon/framework_files
build_src_filter =
    +<src/*.c>
    +<Common/*.c>
    +<Common/framework_files/*.c>
